package aeropuerto;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Nicolás
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipalFull
     */
    public VistaPrincipal()
    {
        initComponents();
        initLookAndFeel();
    }

    private void initLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel1 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        panelGrafico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 17), new java.awt.Dimension(0, 17), new java.awt.Dimension(0, 17));
        btnGenerarVuelos = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnSigVuelo = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnEliminarVuelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel3.add(filler7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel1.add(filler6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Simulación de vuelos");
        jLabel3.setAlignmentX(0.5F);
        jPanel4.add(jLabel3);
        jPanel4.add(filler4);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        panelGrafico.setLayout(new javax.swing.BoxLayout(panelGrafico, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Representación gráfica");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelGrafico.add(jLabel1);

        getContentPane().add(panelGrafico, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones de acción"));
        jPanel2.setMaximumSize(new java.awt.Dimension(110, 129));
        jPanel2.setMinimumSize(new java.awt.Dimension(110, 129));
        jPanel2.setPreferredSize(new java.awt.Dimension(110, 129));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler2);

        btnGenerarVuelos.setText("<html><center>Generar<p>vuelos.</center></html>");
        btnGenerarVuelos.setActionCommand("");
        btnGenerarVuelos.setAlignmentX(0.5F);
        jPanel2.add(btnGenerarVuelos);
        jPanel2.add(filler3);

        btnSigVuelo.setText("<html><center>Eliminar<p>siguiente<p>vuelo.</center></html>");
        btnSigVuelo.setActionCommand("");
        btnSigVuelo.setAlignmentX(0.5F);
        jPanel2.add(btnSigVuelo);
        jPanel2.add(filler1);

        btnEliminarVuelo.setText("<html><center>Eliminar un<p>vuelo<p>específico.</center></html>");
        btnEliminarVuelo.setActionCommand("");
        btnEliminarVuelo.setAlignmentX(0.5F);
        jPanel2.add(btnEliminarVuelo);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnEliminarVuelo()
    {
        return btnEliminarVuelo;
    }

    public JButton getBtnGenerarVuelos()
    {
        return btnGenerarVuelos;
    }

    public JButton getBtnSigVuelo()
    {
        return btnSigVuelo;
    }

    public JPanel getPanelGrafico()
    {
        return panelGrafico;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnGenerarVuelos;
    private javax.swing.JButton btnSigVuelo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
