package aeropuerto;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JProgressBar;

/**
 *
 * @author HikingC7
 */
public class VistaPrincipal2 extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame1
     */
    public VistaPrincipal2()
    {
        initComponents();
        initWindow();
    }

    private void initWindow()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelBotones = new javax.swing.JPanel();
        generarVuelos = new javax.swing.JButton();
        siguienteVuelo = new javax.swing.JButton();
        eliminarVuelo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ProgressBar = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        panel = new javax.swing.JDesktopPane();
        panelEsquema = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.Y_AXIS));

        generarVuelos.setText("Generar vuelos");
        generarVuelos.setActionCommand("generarVuelos");
        generarVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        generarVuelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generarVuelos.setMaximumSize(new java.awt.Dimension(130, 25));
        generarVuelos.setMinimumSize(new java.awt.Dimension(130, 25));
        generarVuelos.setPreferredSize(new java.awt.Dimension(130, 25));
        panelBotones.add(generarVuelos);

        siguienteVuelo.setText("Siguiente vuelo");
        siguienteVuelo.setActionCommand("siguienteVuelo");
        siguienteVuelo.setMaximumSize(new java.awt.Dimension(130, 25));
        siguienteVuelo.setMinimumSize(new java.awt.Dimension(130, 25));
        siguienteVuelo.setPreferredSize(new java.awt.Dimension(130, 25));
        panelBotones.add(siguienteVuelo);

        eliminarVuelo.setText("Eliminar vuelo");
        eliminarVuelo.setActionCommand("eliminarUnVuelo");
        eliminarVuelo.setMaximumSize(new java.awt.Dimension(130, 25));
        eliminarVuelo.setMinimumSize(new java.awt.Dimension(130, 25));
        eliminarVuelo.setPreferredSize(new java.awt.Dimension(130, 25));
        panelBotones.add(eliminarVuelo);

        getContentPane().add(panelBotones, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(ProgressBar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEsquema.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelEsquema.setTitle("Representación de los vuelos");
        panelEsquema.setMaximumSize(new java.awt.Dimension(500, 400));
        panelEsquema.setMinimumSize(new java.awt.Dimension(500, 400));
        panelEsquema.setNormalBounds(new java.awt.Rectangle(20, 20, 0, 0));
        panelEsquema.setPreferredSize(new java.awt.Dimension(500, 400));
        panelEsquema.setVisible(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEsquemaLayout = new javax.swing.GroupLayout(panelEsquema.getContentPane());
        panelEsquema.getContentPane().setLayout(panelEsquemaLayout);
        panelEsquemaLayout.setHorizontalGroup(
            panelEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEsquemaLayout.setVerticalGroup(
            panelEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel.setLayer(panelEsquema, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        jPanel5.add(panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getPanel()
    {
        return panel;
    }

    public JProgressBar getProgressBar()
    {
        return ProgressBar;
    }

    public JButton getEliminarVuelo()
    {
        return eliminarVuelo;
    }

    public JButton getGenerarVuelos()
    {
        return generarVuelos;
    }

    public JInternalFrame getPanelEsquema()
    {
        return panelEsquema;
    }

    public void setPanelEsquema(JInternalFrame panelEsquema)
    {
        this.panelEsquema = panelEsquema;
    }

    public JButton getSiguienteVuelo()
    {
        return siguienteVuelo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton eliminarVuelo;
    private javax.swing.JButton generarVuelos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDesktopPane panel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JInternalFrame panelEsquema;
    private javax.swing.JButton siguienteVuelo;
    // End of variables declaration//GEN-END:variables
}
