package com.sw.view;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Nicolás
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipalFull
     */
    public VistaPrincipal()
    {
        initLookAndFeel();
        initComponents();
    }

    private void initLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        panelGrafico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGenerarVuelos = new javax.swing.JButton();
        btnSigVuelo = new javax.swing.JButton();
        btnEliminarVuelo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Simulación de vuelos");
        jLabel3.setAlignmentX(0.5F);
        jPanel4.add(jLabel3);
        jPanel4.add(filler4);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setContinuousLayout(true);

        jPanel5.setLayout(new java.awt.BorderLayout());

        panelGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder("Representación gráfica"));
        panelGrafico.setLayout(new javax.swing.BoxLayout(panelGrafico, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(panelGrafico, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones de acción"));
        jPanel2.setMaximumSize(new java.awt.Dimension(110, 129));
        jPanel2.setMinimumSize(new java.awt.Dimension(110, 129));
        jPanel2.setPreferredSize(new java.awt.Dimension(110, 129));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnGenerarVuelos.setText("<html><center>Generar<p>vuelos.</center></html>");
        btnGenerarVuelos.setActionCommand("");
        btnGenerarVuelos.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnGenerarVuelos, gridBagConstraints);

        btnSigVuelo.setText("<html><center>Eliminar<p>siguiente<p>vuelo.</center></html>");
        btnSigVuelo.setActionCommand("");
        btnSigVuelo.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnSigVuelo, gridBagConstraints);

        btnEliminarVuelo.setText("<html><center>Eliminar un<p>vuelo<p>específico.</center></html>");
        btnEliminarVuelo.setActionCommand("");
        btnEliminarVuelo.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnEliminarVuelo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jPanel1, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnEliminarVuelo()
    {
        return btnEliminarVuelo;
    }

    public JButton getBtnGenerarVuelos()
    {
        return btnGenerarVuelos;
    }

    public JButton getBtnSigVuelo()
    {
        return btnSigVuelo;
    }

    public JPanel getPanelGrafico()
    {
        return panelGrafico;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnGenerarVuelos;
    private javax.swing.JButton btnSigVuelo;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
