/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeropuerto;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author HikingCarrot7
 */
public class Vista extends javax.swing.JFrame
{

    /**
     * Creates new form Vista2
     */
    public Vista()
    {
        initWindow();
        initComponents();
    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        siguienteVuelo = new javax.swing.JButton();
        panel = new javax.swing.JDesktopPane();
        panelEsquema = new javax.swing.JInternalFrame();
        generarVuelos = new javax.swing.JButton();
        eliminarUnVuelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguienteVuelo.setText("Siguiente vuelo");
        siguienteVuelo.setToolTipText("Eliminar el siguiente vuelo.");
        siguienteVuelo.setActionCommand("siguienteVuelo");
        siguienteVuelo.setMaximumSize(new java.awt.Dimension(120, 30));
        siguienteVuelo.setMinimumSize(new java.awt.Dimension(120, 30));
        siguienteVuelo.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(siguienteVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        panel.setEnabled(false);
        panel.setMaximumSize(new java.awt.Dimension(545, 545));
        panel.setMinimumSize(new java.awt.Dimension(545, 545));
        panel.setPreferredSize(new java.awt.Dimension(545, 545));
        panel.setRequestFocusEnabled(false);

        panelEsquema.setTitle("Representación de los vuelos.");
        panelEsquema.setToolTipText("");
        panelEsquema.setEnabled(false);
        panelEsquema.setMaximumSize(new java.awt.Dimension(545, 545));
        panelEsquema.setMinimumSize(new java.awt.Dimension(545, 545));
        panelEsquema.setNormalBounds(new java.awt.Rectangle(545, 545, 545, 545));
        panelEsquema.setPreferredSize(new java.awt.Dimension(545, 545));
        try
        {
            panelEsquema.setSelected(true);
        } catch (java.beans.PropertyVetoException e1)
        {
            e1.printStackTrace();
        }
        panelEsquema.setVisible(true);

        javax.swing.GroupLayout panelEsquemaLayout = new javax.swing.GroupLayout(panelEsquema.getContentPane());
        panelEsquema.getContentPane().setLayout(panelEsquemaLayout);
        panelEsquemaLayout.setHorizontalGroup(
            panelEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        panelEsquemaLayout.setVerticalGroup(
            panelEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        panel.setLayer(panelEsquema, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(panelEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        generarVuelos.setText("Generar vuelos");
        generarVuelos.setToolTipText("Genera los vuelos.");
        generarVuelos.setActionCommand("generarVuelos");
        generarVuelos.setMaximumSize(new java.awt.Dimension(120, 30));
        generarVuelos.setMinimumSize(new java.awt.Dimension(120, 30));
        generarVuelos.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(generarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        eliminarUnVuelo.setText("Eliminar vuelo");
        eliminarUnVuelo.setToolTipText("Elimina un vuelo en un índice especificado.");
        eliminarUnVuelo.setActionCommand("eliminarUnVuelo");
        eliminarUnVuelo.setMaximumSize(new java.awt.Dimension(120, 30));
        eliminarUnVuelo.setMinimumSize(new java.awt.Dimension(120, 30));
        eliminarUnVuelo.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(eliminarUnVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getPanel()
    {
        return panel;
    }

    public JInternalFrame getPanelEsquema()
    {
        return panelEsquema;
    }

    public void setPanelEsquema(JInternalFrame panelEsquema)
    {
        this.panelEsquema = panelEsquema;
    }

    public JButton getSiguienteVuelo()
    {
        return siguienteVuelo;
    }

    public JButton getGenerarVuelos()
    {
        return generarVuelos;
    }

    public JButton getEliminarUnVuelo()
    {
        return eliminarUnVuelo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarUnVuelo;
    private javax.swing.JButton generarVuelos;
    private javax.swing.JDesktopPane panel;
    private javax.swing.JInternalFrame panelEsquema;
    private javax.swing.JButton siguienteVuelo;
    // End of variables declaration//GEN-END:variables
}
