package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author HikingCarrot7
 */
public class VistaEliminarContacto extends JDialog
{

    public VistaEliminarContacto(Window owner)
    {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        GridBagConstraints gridBagConstraints;

        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        lblNombre = new JLabel();
        jLabel3 = new JLabel();
        lblEdad = new JLabel();
        jLabel5 = new JLabel();
        lblCorreo = new JLabel();
        jPanel3 = new JPanel();
        jPanel1 = new JPanel();
        jPanel5 = new JPanel();
        jLabel7 = new JLabel();
        panelBotones = new JPanel();
        btnEliminar = new JButton();
        btnCancelar = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos encontrados del usuario");
        setMinimumSize(new Dimension(530, 235));
        setPreferredSize(new Dimension(530, 235));

        jPanel2.setBorder(BorderFactory.createTitledBorder("Datos del usuario"));
        jPanel2.setLayout(new GridBagLayout());

        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(20, 35, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(20, 5, 5, 35);
        jPanel2.add(lblNombre, gridBagConstraints);

        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText("Edad:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 35, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 35);
        jPanel2.add(lblEdad, gridBagConstraints);

        jLabel5.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel5.setText("Correo electrónico:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 35, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 35);
        jPanel2.add(lblCorreo, gridBagConstraints);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel2, BorderLayout.CENTER);

        jPanel1.setLayout(new GridBagLayout());

        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/logo_fmat.png"))); // NOI18N
        jLabel7.setText("Powered by:");
        jLabel7.setHorizontalTextPosition(SwingConstants.LEFT);
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5, new GridBagConstraints());

        panelBotones.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnEliminar.setText("Eliminar");
        panelBotones.add(btnEliminar);

        btnCancelar.setText("Cancelar");
        panelBotones.add(btnCancelar);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(panelBotones, gridBagConstraints);

        getContentPane().add(jPanel1, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnEliminar()
    {
        return btnEliminar;
    }

    public JButton getBtnCancelar()
    {
        return btnCancelar;
    }

    public JLabel getLblCorreo()
    {
        return lblCorreo;
    }

    public JLabel getLblEdad()
    {
        return lblEdad;
    }

    public JLabel getLblNombre()
    {
        return lblNombre;
    }

    public JPanel getPanelBotones()
    {
        return panelBotones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancelar;
    private JButton btnEliminar;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel7;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel5;
    private JLabel lblCorreo;
    private JLabel lblEdad;
    private JLabel lblNombre;
    private JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
