package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HikingCarrot7
 */
public class VistaEliminarContacto extends JDialog
{

    public VistaEliminarContacto(Window owner)
    {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        jPanel4 = new JPanel();
        jPanel3 = new JPanel();
        btnEliminar = new JButton();
        btnCancelar = new JButton();
        panelTitulo = new JPanel();
        jScrollPane1 = new JScrollPane();
        tablaListaContactos = new JTable();

        setTitle("Listado de contactos");
        setMinimumSize(new Dimension(450, 325));
        setPreferredSize(new Dimension(450, 325));

        jPanel1.setLayout(new GridLayout(1, 0));

        jPanel4.setLayout(new FlowLayout(FlowLayout.LEFT));
        jPanel1.add(jPanel4);

        jPanel3.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnEliminar.setText("Eliminar");
        jPanel3.add(btnEliminar);

        btnCancelar.setText("Cancelar");
        jPanel3.add(btnCancelar);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, BorderLayout.SOUTH);

        panelTitulo.setBorder(BorderFactory.createTitledBorder("Eliminar contacto(s)"));
        panelTitulo.setLayout(new BorderLayout());

        tablaListaContactos.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Nombre", "Edad", "Correo electrónico"
            }
        ));
        jScrollPane1.setViewportView(tablaListaContactos);

        panelTitulo.add(jScrollPane1, BorderLayout.CENTER);

        getContentPane().add(panelTitulo, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCancelar()
    {
        return btnCancelar;
    }

    public JButton getBtnEliminar()
    {
        return btnEliminar;
    }

    public JTable getTablaListaContactos()
    {
        return tablaListaContactos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancelar;
    private JButton btnEliminar;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JPanel panelTitulo;
    private JTable tablaListaContactos;
    // End of variables declaration//GEN-END:variables
}
