package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author HikingCarrot7
 */
public class VistaPrincipal extends JFrame
{

    public VistaPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        mnItmListarTodosUsuarios = new JMenuItem();
        mnItmListarMisContactos = new JMenuItem();
        jMenu2 = new JMenu();
        mnItmBuscarUsuario = new JMenuItem();
        mnItmEliminarContacto = new JMenuItem();
        mnItmEliminarCuenta = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú principal");
        setMinimumSize(new Dimension(600, 335));
        setPreferredSize(new Dimension(600, 335));

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, BorderLayout.CENTER);

        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT));

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/logo_fmat.png"))); // NOI18N
        jLabel2.setText("Powered by:");
        jLabel2.setToolTipText("Terraria 1.4");
        jLabel2.setHorizontalTextPosition(SwingConstants.LEFT);
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, BorderLayout.PAGE_END);

        jMenu1.setText("Archivo");

        mnItmListarTodosUsuarios.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_T, InputEvent.CTRL_MASK));
        mnItmListarTodosUsuarios.setText("Listar todo");
        jMenu1.add(mnItmListarTodosUsuarios);

        mnItmListarMisContactos.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
        mnItmListarMisContactos.setText("Listar mis contactos");
        jMenu1.add(mnItmListarMisContactos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        mnItmBuscarUsuario.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F, InputEvent.CTRL_MASK));
        mnItmBuscarUsuario.setText("Buscar usuario");
        jMenu2.add(mnItmBuscarUsuario);

        mnItmEliminarContacto.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_D, InputEvent.CTRL_MASK));
        mnItmEliminarContacto.setText("Eliminar contacto");
        jMenu2.add(mnItmEliminarContacto);

        mnItmEliminarCuenta.setText("Eliminar cuenta");
        jMenu2.add(mnItmEliminarCuenta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMnItmBuscarUsuario()
    {
        return mnItmBuscarUsuario;
    }

    public JMenuItem getMnItmEliminarContacto()
    {
        return mnItmEliminarContacto;
    }

    public JMenuItem getMnItmEliminarCuenta()
    {
        return mnItmEliminarCuenta;
    }

    public JMenuItem getMnItmListarMisContactos()
    {
        return mnItmListarMisContactos;
    }

    public JMenuItem getMnItmListarTodosUsuarios()
    {
        return mnItmListarTodosUsuarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JMenuItem mnItmBuscarUsuario;
    private JMenuItem mnItmEliminarContacto;
    private JMenuItem mnItmEliminarCuenta;
    private JMenuItem mnItmListarMisContactos;
    private JMenuItem mnItmListarTodosUsuarios;
    // End of variables declaration//GEN-END:variables
}
