package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author HikingCarrot7
 */
public class VistaPrincipal extends JFrame
{

    public VistaPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        panelBotones = new JPanel();
        btnBuscarUsuario = new JButton();
        btnVerUsuariosRegistrados = new JButton();
        btnVerContactos = new JButton();
        btnEditarCuenta = new JButton();
        btnEliminarContacto = new JButton();
        btnEliminarCuenta = new JButton();
        jPanel1 = new JPanel();
        btnCerrarSesion = new JButton();
        jMenuBar1 = new JMenuBar();
        mnArchivo = new JMenu();
        mnItmListarTodosUsuarios = new JMenuItem();
        mnItmListarMisContactos = new JMenuItem();
        mnEdicion = new JMenu();
        mnItmBuscarUsuario = new JMenuItem();
        mnItmEliminarContacto = new JMenuItem();
        mnItmEliminarCuenta = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú principal");
        setMinimumSize(new Dimension(675, 420));
        setPreferredSize(new Dimension(675, 420));

        jPanel2.setLayout(new BorderLayout());

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, BorderLayout.NORTH);

        panelBotones.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelBotones.setLayout(new GridLayout(2, 3, 15, 15));

        btnBuscarUsuario.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/buscar.png"))); // NOI18N
        btnBuscarUsuario.setText("Buscar usuario");
        btnBuscarUsuario.setContentAreaFilled(false);
        btnBuscarUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBuscarUsuario.setFocusPainted(false);
        btnBuscarUsuario.setHorizontalTextPosition(SwingConstants.CENTER);
        btnBuscarUsuario.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/buscar_rollover.png"))); // NOI18N
        btnBuscarUsuario.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnBuscarUsuario);

        btnVerUsuariosRegistrados.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/ver_todos_usuarios.png"))); // NOI18N
        btnVerUsuariosRegistrados.setText("Ver usuarios registrados");
        btnVerUsuariosRegistrados.setContentAreaFilled(false);
        btnVerUsuariosRegistrados.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnVerUsuariosRegistrados.setFocusPainted(false);
        btnVerUsuariosRegistrados.setHorizontalTextPosition(SwingConstants.CENTER);
        btnVerUsuariosRegistrados.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/ver_todos_usuarios_rollover.png"))); // NOI18N
        btnVerUsuariosRegistrados.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnVerUsuariosRegistrados);

        btnVerContactos.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/contactos.png"))); // NOI18N
        btnVerContactos.setText("Ver contactos");
        btnVerContactos.setContentAreaFilled(false);
        btnVerContactos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnVerContactos.setFocusPainted(false);
        btnVerContactos.setHorizontalTextPosition(SwingConstants.CENTER);
        btnVerContactos.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/contactos_rollover.png"))); // NOI18N
        btnVerContactos.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnVerContactos);

        btnEditarCuenta.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/editar_perfil.png"))); // NOI18N
        btnEditarCuenta.setText("Editar cuenta");
        btnEditarCuenta.setContentAreaFilled(false);
        btnEditarCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditarCuenta.setFocusPainted(false);
        btnEditarCuenta.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEditarCuenta.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/editar_perfil_rollover.png"))); // NOI18N
        btnEditarCuenta.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnEditarCuenta);

        btnEliminarContacto.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/eliminar_contacto.png"))); // NOI18N
        btnEliminarContacto.setText("Eliminar contacto");
        btnEliminarContacto.setContentAreaFilled(false);
        btnEliminarContacto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminarContacto.setFocusPainted(false);
        btnEliminarContacto.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEliminarContacto.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/eliminar_contacto_rollover.png"))); // NOI18N
        btnEliminarContacto.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnEliminarContacto);

        btnEliminarCuenta.setIcon(new ImageIcon(getClass().getResource("/com/sw/img/eliminar_cuenta.png"))); // NOI18N
        btnEliminarCuenta.setText("Eliminar mi cuenta");
        btnEliminarCuenta.setContentAreaFilled(false);
        btnEliminarCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminarCuenta.setFocusPainted(false);
        btnEliminarCuenta.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEliminarCuenta.setRolloverIcon(new ImageIcon(getClass().getResource("/com/sw/img/eliminar_cuenta_rollover.png"))); // NOI18N
        btnEliminarCuenta.setVerticalTextPosition(SwingConstants.BOTTOM);
        panelBotones.add(btnEliminarCuenta);

        jPanel2.add(panelBotones, BorderLayout.CENTER);

        getContentPane().add(jPanel2, BorderLayout.CENTER);

        jPanel1.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnCerrarSesion.setText("Cerrar sesión");
        jPanel1.add(btnCerrarSesion);

        getContentPane().add(jPanel1, BorderLayout.PAGE_END);

        mnArchivo.setText("Archivo");

        mnItmListarTodosUsuarios.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_T, InputEvent.CTRL_MASK));
        mnItmListarTodosUsuarios.setText("Listar todo");
        mnArchivo.add(mnItmListarTodosUsuarios);

        mnItmListarMisContactos.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
        mnItmListarMisContactos.setText("Listar mis contactos");
        mnArchivo.add(mnItmListarMisContactos);

        jMenuBar1.add(mnArchivo);

        mnEdicion.setText("Edición");

        mnItmBuscarUsuario.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F, InputEvent.CTRL_MASK));
        mnItmBuscarUsuario.setText("Buscar usuario");
        mnEdicion.add(mnItmBuscarUsuario);

        mnItmEliminarContacto.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_D, InputEvent.CTRL_MASK));
        mnItmEliminarContacto.setText("Eliminar contacto");
        mnEdicion.add(mnItmEliminarContacto);

        mnItmEliminarCuenta.setText("Eliminar cuenta");
        mnEdicion.add(mnItmEliminarCuenta);

        jMenuBar1.add(mnEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMnItmBuscarUsuario()
    {
        return mnItmBuscarUsuario;
    }

    public JMenuItem getMnItmEliminarContacto()
    {
        return mnItmEliminarContacto;
    }

    public JMenuItem getMnItmEliminarCuenta()
    {
        return mnItmEliminarCuenta;
    }

    public JMenuItem getMnItmListarMisContactos()
    {
        return mnItmListarMisContactos;
    }

    public JMenuItem getMnItmListarTodosUsuarios()
    {
        return mnItmListarTodosUsuarios;
    }

    public JButton getBtnBuscarUsuario()
    {
        return btnBuscarUsuario;
    }

    public JButton getBtnEditarCuenta()
    {
        return btnEditarCuenta;
    }

    public JButton getBtnEliminarContacto()
    {
        return btnEliminarContacto;
    }

    public JButton getBtnEliminarCuenta()
    {
        return btnEliminarCuenta;
    }

    public JButton getBtnListarMisContactos()
    {
        return btnVerContactos;
    }

    public JButton getBtnMostrarTodosUsuarios()
    {
        return btnVerUsuariosRegistrados;
    }

    public JButton getBtnCerrarSesion()
    {
        return btnCerrarSesion;
    }

    public JMenu getMnArchivo()
    {
        return mnArchivo;
    }

    public JMenu getMnEdicion()
    {
        return mnEdicion;
    }

    public JPanel getPanelBotones()
    {
        return panelBotones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBuscarUsuario;
    private JButton btnCerrarSesion;
    private JButton btnEditarCuenta;
    private JButton btnEliminarContacto;
    private JButton btnEliminarCuenta;
    private JButton btnVerContactos;
    private JButton btnVerUsuariosRegistrados;
    private JLabel jLabel1;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JMenu mnArchivo;
    private JMenu mnEdicion;
    private JMenuItem mnItmBuscarUsuario;
    private JMenuItem mnItmEliminarContacto;
    private JMenuItem mnItmEliminarCuenta;
    private JMenuItem mnItmListarMisContactos;
    private JMenuItem mnItmListarTodosUsuarios;
    private JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
