package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Nicolás
 */
public class Vista extends JFrame
{

    public Vista()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        GridBagConstraints gridBagConstraints;

        grupoBusqueda = new ButtonGroup();
        grupoRecorrido = new ButtonGroup();
        grupoCreacionGrafo = new ButtonGroup();
        jSplitPane1 = new JSplitPane();
        jSplitPane2 = new JSplitPane();
        jPanel3 = new JPanel();
        jScrollPane1 = new JScrollPane();
        panelGraficoGrafo = new JPanel();
        jPanel5 = new JPanel();
        jScrollPane2 = new JScrollPane();
        panelRecorrido = new JPanel();
        jPanel7 = new JPanel();
        panelPreparacion = new JPanel();
        jLabel14 = new JLabel();
        jRadioButton5 = new JRadioButton();
        jRadioButton6 = new JRadioButton();
        btnGenerar = new JButton();
        panelManipulacionGrafo = new JPanel();
        jLabel1 = new JLabel();
        txtNuevoVertice = new JTextField();
        btnCrearVertice = new JButton();
        jLabel2 = new JLabel();
        txtCrearArcoFrom = new JTextField();
        txtCrearArcoTo = new JTextField();
        jLabel3 = new JLabel();
        btnCrearArco = new JButton();
        jSeparator1 = new JSeparator();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        txtEliminarVertice = new JTextField();
        btnEliminarVertice = new JButton();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        eliminarArcoFrom = new JTextField();
        eliminarArcoTo = new JTextField();
        btnEliminarArco = new JButton();
        jSeparator2 = new JSeparator();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        txtAdyacenciaArcoFrom = new JTextField();
        txtAdyacenciaArcoTo = new JTextField();
        btnChecarAdyacencia = new JButton();
        jSeparator3 = new JSeparator();
        jLabel12 = new JLabel();
        txtVerticeBuscar = new JTextField();
        btnBuscar = new JButton();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jSeparator4 = new JSeparator();
        jLabel13 = new JLabel();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        btnRecorrerGrafo = new JButton();
        jPanel2 = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos!");
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));

        jSplitPane1.setDividerLocation(385);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(1.0);
        jSplitPane2.setContinuousLayout(true);

        jPanel3.setBorder(BorderFactory.createTitledBorder("Grafo"));
        jPanel3.setLayout(new BorderLayout());

        panelGraficoGrafo.setBackground(new Color(255, 255, 255));
        panelGraficoGrafo.setMinimumSize(new Dimension(0, 0));
        panelGraficoGrafo.setPreferredSize(new Dimension(0, 0));
        panelGraficoGrafo.setLayout(new BorderLayout());
        jScrollPane1.setViewportView(panelGraficoGrafo);

        jPanel3.add(jScrollPane1, BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel3);

        jPanel5.setBorder(BorderFactory.createTitledBorder("Recorrido"));
        jPanel5.setLayout(new BorderLayout());

        panelRecorrido.setBackground(new Color(255, 255, 255));
        panelRecorrido.setMinimumSize(new Dimension(550, 550));
        panelRecorrido.setPreferredSize(new Dimension(0, 0));
        panelRecorrido.setLayout(new BorderLayout());
        jScrollPane2.setViewportView(panelRecorrido);

        jPanel5.add(jScrollPane2, BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel5);

        jSplitPane1.setRightComponent(jSplitPane2);

        jPanel7.setBorder(BorderFactory.createTitledBorder("Entrada de los datos"));
        jPanel7.setLayout(new BorderLayout());

        panelPreparacion.setBorder(BorderFactory.createTitledBorder("Preparación"));
        panelPreparacion.setLayout(new GridBagLayout());

        jLabel14.setText("Generar grafo con:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelPreparacion.add(jLabel14, gridBagConstraints);

        grupoCreacionGrafo.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Matriz de adyacencia");
        jRadioButton5.setActionCommand("matriz");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelPreparacion.add(jRadioButton5, gridBagConstraints);

        grupoCreacionGrafo.add(jRadioButton6);
        jRadioButton6.setText("Lista de adyacencia");
        jRadioButton6.setActionCommand("lista");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelPreparacion.add(jRadioButton6, gridBagConstraints);

        btnGenerar.setText("Generar");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelPreparacion.add(btnGenerar, gridBagConstraints);

        jPanel7.add(panelPreparacion, BorderLayout.NORTH);

        panelManipulacionGrafo.setBorder(BorderFactory.createTitledBorder("Manipulación del grafo"));
        panelManipulacionGrafo.setLayout(new GridBagLayout());

        jLabel1.setText("Crear vértice:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtNuevoVertice, gridBagConstraints);

        btnCrearVertice.setText("Crear vértice");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnCrearVertice, gridBagConstraints);

        jLabel2.setText("Crear arco:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtCrearArcoFrom, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtCrearArcoTo, gridBagConstraints);

        jLabel3.setText("A:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel3, gridBagConstraints);

        btnCrearArco.setText("Crear arco");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnCrearArco, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 15, 0);
        panelManipulacionGrafo.add(jSeparator1, gridBagConstraints);

        jLabel4.setText("De:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Eliminar vértice:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtEliminarVertice, gridBagConstraints);

        btnEliminarVertice.setText("Eliminar vértice");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnEliminarVertice, gridBagConstraints);

        jLabel6.setText("Eliminar arco:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel6, gridBagConstraints);

        jLabel7.setText("De:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel7, gridBagConstraints);

        jLabel8.setText("A:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(eliminarArcoFrom, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(eliminarArcoTo, gridBagConstraints);

        btnEliminarArco.setText("Eliminar arco");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnEliminarArco, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 15, 0);
        panelManipulacionGrafo.add(jSeparator2, gridBagConstraints);

        jLabel9.setText("Revisar adyacencia:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel9, gridBagConstraints);

        jLabel10.setText("De:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel10, gridBagConstraints);

        jLabel11.setText("A:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtAdyacenciaArcoFrom, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtAdyacenciaArcoTo, gridBagConstraints);

        btnChecarAdyacencia.setText("¿Adyacentes?");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnChecarAdyacencia, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 15, 0);
        panelManipulacionGrafo.add(jSeparator3, gridBagConstraints);

        jLabel12.setText("Buscar un vértice por:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(txtVerticeBuscar, gridBagConstraints);

        btnBuscar.setText("Buscar");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnBuscar, gridBagConstraints);

        grupoBusqueda.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Anchura");
        jRadioButton1.setActionCommand("anchura");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jRadioButton1, gridBagConstraints);

        grupoBusqueda.add(jRadioButton2);
        jRadioButton2.setText("Profundidad");
        jRadioButton2.setActionCommand("profundidad");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jRadioButton2, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 15, 0);
        panelManipulacionGrafo.add(jSeparator4, gridBagConstraints);

        jLabel13.setText("Recorrer grafo por:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jLabel13, gridBagConstraints);

        grupoRecorrido.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Anchura");
        jRadioButton3.setActionCommand("anchura");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jRadioButton3, gridBagConstraints);

        grupoRecorrido.add(jRadioButton4);
        jRadioButton4.setText("Profundidad");
        jRadioButton4.setActionCommand("profundidad");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(jRadioButton4, gridBagConstraints);

        btnRecorrerGrafo.setText("Recorrer");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 0, 0, 0);
        panelManipulacionGrafo.add(btnRecorrerGrafo, gridBagConstraints);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panelManipulacionGrafo.add(jPanel2, gridBagConstraints);

        jPanel7.add(panelManipulacionGrafo, BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel7);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBuscar()
    {
        return btnBuscar;
    }

    public JButton getBtnChecarAdyacencia()
    {
        return btnChecarAdyacencia;
    }

    public JButton getBtnCrearArco()
    {
        return btnCrearArco;
    }

    public JButton getBtnCrearVertice()
    {
        return btnCrearVertice;
    }

    public JButton getBtnEliminarArco()
    {
        return btnEliminarArco;
    }

    public JButton getBtnEliminarVertice()
    {
        return btnEliminarVertice;
    }

    public JButton getBtnGenerar()
    {
        return btnGenerar;
    }

    public JButton getBtnRecorrerGrafo()
    {
        return btnRecorrerGrafo;
    }

    public ButtonGroup getGrupoBusqueda()
    {
        return grupoBusqueda;
    }

    public ButtonGroup getGrupoCreacionGrafo()
    {
        return grupoCreacionGrafo;
    }

    public ButtonGroup getGrupoRecorrido()
    {
        return grupoRecorrido;
    }

    public JPanel getPanelGraficoGrafo()
    {
        return panelGraficoGrafo;
    }

    public JPanel getPanelManipulacionGrafo()
    {
        return panelManipulacionGrafo;
    }

    public JPanel getPanelRecorrido()
    {
        return panelRecorrido;
    }

    public JPanel getPanelPreparacion()
    {
        return panelPreparacion;
    }

    public JTextField getTxtAdyacenciaArcoFrom()
    {
        return txtAdyacenciaArcoFrom;
    }

    public JTextField getTxtAdyacenciaArcoTo()
    {
        return txtAdyacenciaArcoTo;
    }

    public JTextField getTxtCrearArcoFrom()
    {
        return txtCrearArcoFrom;
    }

    public JTextField getTxtCrearArcoTo()
    {
        return txtCrearArcoTo;
    }

    public JTextField getTxtEliminarArcoFrom()
    {
        return eliminarArcoFrom;
    }

    public JTextField getTxtEliminarArcoTo()
    {
        return eliminarArcoTo;
    }

    public JTextField getTxtEliminarVertice()
    {
        return txtEliminarVertice;
    }

    public JTextField getTxtNuevoVertice()
    {
        return txtNuevoVertice;
    }

    public JTextField getTxtVerticeBuscar()
    {
        return txtVerticeBuscar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBuscar;
    private JButton btnChecarAdyacencia;
    private JButton btnCrearArco;
    private JButton btnCrearVertice;
    private JButton btnEliminarArco;
    private JButton btnEliminarVertice;
    private JButton btnGenerar;
    private JButton btnRecorrerGrafo;
    private JTextField eliminarArcoFrom;
    private JTextField eliminarArcoTo;
    private ButtonGroup grupoBusqueda;
    private ButtonGroup grupoCreacionGrafo;
    private ButtonGroup grupoRecorrido;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel5;
    private JPanel jPanel7;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton4;
    private JRadioButton jRadioButton5;
    private JRadioButton jRadioButton6;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator4;
    private JSplitPane jSplitPane1;
    private JSplitPane jSplitPane2;
    private JPanel panelGraficoGrafo;
    private JPanel panelManipulacionGrafo;
    private JPanel panelPreparacion;
    private JPanel panelRecorrido;
    private JTextField txtAdyacenciaArcoFrom;
    private JTextField txtAdyacenciaArcoTo;
    private JTextField txtCrearArcoFrom;
    private JTextField txtCrearArcoTo;
    private JTextField txtEliminarVertice;
    private JTextField txtNuevoVertice;
    private JTextField txtVerticeBuscar;
    // End of variables declaration//GEN-END:variables
}
